#! /bin/sh

#AUTOSTART
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap de &
nitrogen --restore &
~/.config/polybar/launch.sh &
picom --experimental-backends -b --config ~/.config/picom/picom.conf &
wmname LG3D &

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DVI-D-1 -d 6 7 8 9

bspc rule -a TelegramDesktop desktop=6 follow=on 
bspc rule -a discord desktop=7 follow=on
bspc rule -a spotify desktop=7 follow=on

bspc config border_width         0
bspc config window_gap			10

bspc config split_ratio          	0.54
bspc config focus_follows_pointer	false
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

