#! /bin/sh

#AUTOSTART
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap de &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
~/.config/polybar/launch.sh &
picom -b --config ~/.config/picom/picom.conf &
echo 0 > /sys/class/leds/platform\:\:micmute/brightness &
wmname LG3D &

if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]
then
        xrandr --output eDP --mode 1920x1080 --pos 320x1440 --output HDMI-A-0 --primary --mode 2560x1440 --pos 0x0
else
        xrandr --output eDP --primary --mode 1920x1080
fi

if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]
then
        bspc monitor HDMI-A-0 -d 1 2 3 4 5
        bspc monitor eDP -d 6 7 8 9
else
        bspc monitor eDP -d 1 2 3 4 5
fi

bspc rule -a TelegramDesktop desktop=6 follow=on 
bspc rule -a discord desktop=7 follow=on
bspc rule -a spotify desktop=7 follow=on

bspc config border_width         0
bspc config window_gap			10

bspc config split_ratio          	0.54
bspc config focus_follows_pointer	false
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

